package document

type Method string

const (
	CREATE_DOCUMENT Method = "CREATE_DOCUMENT"
	READ_DOCUMENT   Method = "READ_DOCUMENT"
	UPDATE_DOCUMENT Method = "UPDATE_DOCUMENT"
	DELETE_DOCUMENT Method = "DELETE_DOCUMENT"

	CREATE_COLLECTION Method = "CREATE_COLLECTION"
	READ_COLLECTION   Method = "READ_COLLECTION"
	QUERY_COLLECTION  Method = "QUERY_COLLECTION"
	UPDATE_COLLECTION Method = "UPDATE_COLLECTION"
	DELETE_COLLECTION Method = "DELETE_COLLECTION"
)

type DocumentDriver struct {
}
